#Made for HyperGaming but i want anyone to be able to use this basic feature!
#
#Made by HyperGaming18
#
# Visit our website: https://hypergaming.co.uk/
#
#Version 1.1


Discord: https://discord.gg/FVt7pGT
